---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - "/Applications/Utilities/Activity Monitor.app"
    - /Applications/Skype.app
    - /Applications/Adium.app
    - /Applications/Safari.app
    - /Applications/iTerm.app
    - /Applications/Atom.app
    - /Applications/Spotify.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: ann315
    git_user_email: shakespearefan531@gmail.com

  # Make sure the path prefix is there for the legit/hub shims
  - role: env_path
  - role: legit
  - role: hub

  - role: brew_package
    package_name: vim
  - role: brew_package
    package_name: ack
  - role: brew_package
    package_name: autossh
  - role: brew_package
    package_name: coreutils
  - role: brew_package
    package_name: findutils
  - role: brew_package
    package_name: imagemagick
  - role: brew_package
    package_name: pcre
  - role: brew_package
    package_name: sqlite
  - role: brew_package
    package_name: wget
  - role: brew_package
    package_name: docker
  - role: brew_package
    package_name: boot2docker

  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv

  # - role: cask_package
  #   package_name: java
  # - role: brew_package
  #   package_name: android-sdk

  ## databases
  - role: brew_package
    package_name: postgres
  - role: brew_package
    package_name: mongodb

  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt

  # gui
  ## text editors
  - role: cask_package
    package_name: atom

  # misc tools
  - role: cask_package
    package_name: skitch
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: skype
  - role: cask_package
    package_name: adium
  - role: cask_package
    package_name: vlc
  - role: cask_package
    package_name: iterm2


# Ruby gems
- include: ruby_gem_packages.yml

# Node packages
- include: node_npm_packages.yml

# Atom packages
- include: atom_packages.yml
